/* ============================================================
   Role Dashboards — data model (6 roles)
   Edit content here; role-render.js turns it into the shell.
   kpis:       [label, value, trend, isDown?]
   attention:  [icon, level('warn'|'ok'|''), title, meta]
   quick:      [icon, label, isPrimary?]
   widget:     {type:'chart'|'table'|'feed'|'schedule'|'instbreak', ...}
   ============================================================ */
window.ROLE_DATA = {

  architect: {
    roleLabel: 'Platform Architect', who: 'Ada O.', avatar: 'AO',
    tenant: 'SchoolWithEase', tenantSub: 'All tenants', tenantSwitch: false,
    crumb: ['Platform', 'Overview'],
    rail: ['◉','▦','✦','◷','⚙'], railOn: 0,
    nav: [
      {group:'Platform'},
      {t:'Dashboard', k:'dash', on:true},
      {t:'Schools', k:'schools', cnt:'1.2k'},
      {t:'Users', k:'users'},
      {t:'Plans & Billing', k:'billing'},
      {group:'Insight'},
      {t:'Analytics', k:'analytics'},
      {t:'Support', k:'support', cnt:'18'},
      {t:'Audit Logs', k:'audit'},
      {t:'Administration', k:'admin'},
    ],
    hello: 'Platform overview',
    kpis: [['Total schools','1,284'],['Active schools','1,190','▲ 4%'],['Total users','312k','▲ 8%'],['MRR','$84.2k','▲ 6%'],['Renewals due','37'],['Open tickets','18','▲ 3','down']],
    attention: [
      ['◷','warn','12 schools near expiry','Subscriptions lapse within 7 days'],
      ['◔','warn','5 onboarding stalled','No activity for 14+ days'],
      ['!','warn','3 critical support tickets','Avg wait 9h'],
      ['$','','4 payment failures','Retry scheduled'],
    ],
    quick: [['＋','Create School',true],['▤','Manage Plans'],['📣','Broadcast Message'],['❏','View Audit Logs']],
    wPrimary: {type:'chart', title:'School growth (12 mo)', heights:[35,42,40,52,58,55,64,70,68,78,84,92], hl:11, x:['J','F','M','A','M','J','J','A','S','O','N','D']},
    wSecondary: {type:'instbreak', title:'By institution type', rows:[['Secondary',512],['Primary',388],['University',96],['Training',141],['Nursery',147]]},
    deeperKey: 'schools', deeperTitle:'Schools', deeperSub:'1,284 total · filter by status, type, plan',
  },

  owner: {
    roleLabel: 'Proprietor', who: 'Mr Bello', avatar: 'MB',
    tenant: 'Greenfield Academy', tenantSub: 'switch school', tenantSwitch: true,
    crumb: ['Greenfield Academy', 'Dashboard'],
    rail: ['◉','♟','▤','$','✉','⚙'], railOn: 0,
    nav: [
      {t:'Dashboard', k:'dash', on:true},
      {group:'People'},
      {t:'Students', k:'students', cnt:'1.4k'},
      {t:'Staff', k:'staff', cnt:'96'},
      {group:'Run the school'},
      {t:'Academics', k:'academics'},
      {t:'Finance', k:'finance'},
      {t:'Communication', k:'comm'},
      {group:'Insight'},
      {t:'Analytics', k:'analytics'},
      {t:'Reports', k:'reports'},
    ],
    hello: 'Good morning, Mr Bello',
    kpis: [['Total students','1,420','▲ 3%'],['Total staff','96'],['Revenue (mo)','₦12.4M','▲ 9%'],['Outstanding fees','₦3.1M','','down'],['Attendance','94%'],['Upcoming events','5']],
    attention: [
      ['◔','warn','38 admission applications','Pending review'],
      ['$','warn','₦3.1M outstanding fees','142 students'],
      ['♟','','6 staff on leave today','2 unfilled classes'],
      ['◷','','Term ends in 3 weeks','Plan results & reports'],
    ],
    quick: [['＋','Add Student',true],['♟','Add Staff'],['📣','Send Announcement'],['▤','View Reports']],
    wPrimary: {type:'chart', title:'Enrollment growth', heights:[40,44,48,46,55,60,58,66,70,72,76,80], hl:11, x:['T1','','','','','','','','','','','Now']},
    wSecondary: {type:'feed', title:'Recent activity', rows:[['₦240k fees collected','12 min ago'],['New admission: J. Okoro','1h ago'],['Announcement sent','3h ago'],['Staff: 2 lesson notes uploaded','5h ago']]},
    deeperKey: 'students', deeperTitle:'Admission applications', deeperSub:'38 pending · review & decide',
  },

  teacher: {
    roleLabel: 'Teacher', who: 'Ms Cole', avatar: 'MC',
    tenant: 'Greenfield Academy', tenantSub: '', tenantSwitch: false,
    crumb: ['Greenfield Academy', 'Dashboard'],
    rail: ['◉','▦','◷','✎','⚙'], railOn: 0,
    nav: [
      {t:'Dashboard', k:'dash', on:true},
      {group:'Teaching'},
      {t:'My Classes', k:'classes', cnt:'4'},
      {t:'Timetable', k:'timetable'},
      {t:'Attendance', k:'attendance'},
      {t:'Assignments', k:'assignments', cnt:'12'},
      {t:'Grading', k:'grading'},
      {group:'More'},
      {t:'Resources', k:'resources'},
      {t:'Messages', k:'messages', cnt:'3'},
    ],
    hello: 'Good morning, Ms Cole',
    kpis: [['Classes today','4'],['Students today','128'],['Assignments pending','12','','down'],['Attendance submitted','2 of 4']],
    attention: [
      ['✎','warn','Grade 12 Biology assignments','Due back to students Fri'],
      ['◷','warn','Submit attendance · 2 classes','11B · 10A'],
      ['❏','','Upload lesson notes','Chemistry 10A'],
      ['✉','ok','3 student questions','In Biology forum'],
    ],
    quick: [['✓','Take Attendance',true],['＋','Create Assignment'],['#','Enter Scores'],['✉','Send Message']],
    wPrimary: {type:'schedule', title:"Today's schedule", rows:[['08:30','Biology · 11B','Room 204',false],['10:00','Chemistry · 10A','Lab 2',false],['12:15','Biology · 11A','Room 204',true],['14:00','Form time · 11B','Room 109',true]]},
    wSecondary: {type:'feed', title:'Student activity', rows:[['M. Jones submitted assignment','8 min ago'],['Question in Biology forum','25 min ago'],['S. Kemi submitted assignment','1h ago'],['New message from parent','2h ago']]},
    deeperKey: 'attendance', deeperTitle:'Take attendance', deeperSub:'Biology · 11B · 08:30 · 28 students',
  },

  student: {
    roleLabel: 'Student', who: 'Maya Chen', avatar: 'MC',
    tenant: 'Greenfield Academy', tenantSub: '', tenantSwitch: false,
    crumb: ['Greenfield Academy', 'Dashboard'],
    rail: ['◉','◷','✎','▦','✉','⚙'], railOn: 0,
    nav: [
      {t:'Dashboard', k:'dash', on:true},
      {group:'Learning'},
      {t:'Timetable', k:'timetable'},
      {t:'Assignments', k:'assignments', cnt:'4'},
      {t:'Results', k:'results'},
      {t:'Resources (LMS)', k:'lms'},
      {t:'Virtual Classes', k:'virtual'},
      {group:'More'},
      {t:'Messages', k:'messages', cnt:'2'},
    ],
    hello: 'Hi Maya 👋',
    kpis: [['Attendance','96%'],['GPA','3.7'],['Subjects','8'],['Assignments due','4','','down']],
    instKpiLabels: { University:{1:'GPA / credits',2:'Courses'}, Nursery:{1:'Milestones met',2:'Activities'}, Secondary:{1:'GPA',2:'Subjects'} },
    attention: [
      ['✎','warn','Biology lab report','Due tomorrow 5pm'],
      ['✎','','Maths problem set','Due in 3 days'],
      ['◷','ok','Physics virtual class','Starts 11:00 today'],
      ['#','','New result posted','Chemistry test'],
    ],
    quick: [['▶','Join Class',true],['↥','Submit Assignment'],['#','View Results'],['✉','Message Teacher']],
    wPrimary: {type:'schedule', title:"Today's timetable", rows:[['08:30','English','Room 12',false],['10:00','Biology','Lab 1',false],['11:00','Physics (virtual)','Online',true],['13:30','Maths','Room 8',true]]},
    wSecondary: {type:'table', title:'Recent results', head:['Subject','Assessment','Grade'], rows:[['Chemistry','Term test','A'],['English','Essay','B+'],['Biology','Quiz','A−']]},
    deeperKey: 'assignments', deeperTitle:'Assignments', deeperSub:'4 due · 2 submitted this week',
  },

  parent: {
    roleLabel: 'Parent', who: 'Mr Chen', avatar: 'PC',
    tenant: 'Greenfield Academy', tenantSub: '', tenantSwitch: false,
    crumb: ['Greenfield Academy', 'Dashboard'],
    rail: ['◉','♟','#','$','✉','⚙'], railOn: 0,
    multiChild: [{n:'Maya', y:'Year 11', av:'MC'}, {n:'Leo', y:'Year 8', av:'LC'}],
    nav: [
      {t:'Dashboard', k:'dash', on:true},
      {group:'My children'},
      {t:'Results', k:'results'},
      {t:'Attendance', k:'attendance'},
      {t:'Fees', k:'fees', cnt:'!'},
      {group:'School'},
      {t:'Messages', k:'messages', cnt:'2'},
      {t:'Events', k:'events'},
    ],
    hello: 'Welcome back',
    kpis: [['Children','2'],['Attendance','95%'],['Outstanding fees','₦120k','','down'],['Upcoming events','3']],
    attention: [
      ['$','warn','₦120k fees due · Maya','Pay by 14 June'],
      ['#','ok','New result · Leo','Maths: B+'],
      ['◷','','Parents evening','Thu 6pm · book a slot'],
      ['✉','','Message from class teacher','Re: Maya'],
    ],
    quick: [['$','Pay Fees',true],['▤','Download Reports'],['✉','Message School']],
    wPrimary: {type:'table', title:'Latest results', head:['Subject','Assessment','Grade'], rows:[['Chemistry','Term test','A'],['English','Essay','B+'],['Maths','Quiz','B']]},
    wSecondary: {type:'feed', title:'School messages', rows:[['Fee reminder · Maya','1 day ago'],['Trip consent form','2 days ago'],['Term newsletter','4 days ago']]},
    deeperKey: 'results', deeperTitle:'Academic detail', deeperSub:'results & attendance per child',
  },

  bursar: {
    roleLabel: 'Bursar', who: 'Mr Ade', avatar: 'MA',
    tenant: 'Greenfield Academy', tenantSub: '', tenantSwitch: false,
    crumb: ['Greenfield Academy', 'Dashboard'],
    rail: ['◉','$','▤','❏','⚙'], railOn: 0,
    nav: [
      {t:'Dashboard', k:'dash', on:true},
      {group:'Finance'},
      {t:'Fees', k:'fees'},
      {t:'Invoices', k:'invoices', cnt:'27'},
      {t:'Payments', k:'payments'},
      {t:'Scholarships', k:'scholarships'},
      {group:'Insight'},
      {t:'Reports', k:'reports'},
      {t:'Defaulters', k:'defaulters', cnt:'142'},
    ],
    hello: 'Finance · today',
    kpis: [['Payments today','₦480k','▲'],['Outstanding','₦3.1M','','down'],['Revenue (mo)','₦12.4M','▲ 9%'],['Pending invoices','27']],
    attention: [
      ['$','warn','142 fee defaulters','₦3.1M outstanding'],
      ['❏','warn','27 invoices pending send','Term 3'],
      ['◷','','Scholarship review','9 applications'],
      ['↻','ok','Bank reconciliation','Up to date'],
    ],
    quick: [['＋','Record Payment',true],['❏','Generate Invoice'],['▤','Financial Report']],
    wPrimary: {type:'chart', title:'Daily collections (2 wks)', heights:[50,62,45,70,55,30,20,66,72,58,80,64,40,90], hl:13, x:['M','T','W','T','F','S','S','M','T','W','T','F','S','S']},
    wSecondary: {type:'table', title:'Recent payments', head:['Student','Amount','Method'], rows:[['A. Rivera','₦80k','Transfer'],['M. Jones','₦120k','Card'],['S. Kemi','₦40k','Cash']]},
    deeperKey: 'defaulters', deeperTitle:'Fee defaulters', deeperSub:'142 students · ₦3.1M outstanding',
  },

  principal: {
    roleLabel: 'Principal', who: 'Dr Eze', avatar: 'DE',
    tenant: 'Greenfield Academy', tenantSub: '', tenantSwitch: false,
    crumb: ['Greenfield Academy', 'Dashboard'],
    rail: ['◉','♟','▦','◷','⚙'], railOn: 0,
    nav: [
      {t:'Dashboard', k:'dash', on:true},
      {group:'Academic'},
      {t:'Classes', k:'classes'},
      {t:'Attendance', k:'attendance'},
      {t:'Exams', k:'exams', cnt:'3'},
      {t:'Approvals', k:'approvals', cnt:'5'},
      {group:'People & comms'},
      {t:'Staff', k:'staff'},
      {t:'Communication', k:'comm'},
      {t:'Analytics', k:'analytics'},
    ],
    hello: 'Good morning, Dr Eze',
    kpis: [['Students present','1,312','▲'],['Staff present','88 of 96'],['Classes running','42'],['Upcoming exams','3'],['Discipline cases','2','','down']],
    attention: [
      ['✓','warn','5 items await approval','4 results · 1 timetable'],
      ['!','warn','2 discipline cases','Need review today'],
      ['◷','','Exam timetable to confirm','Mock exams · next week'],
      ['◔','','Low attendance · 9A','88% this week'],
    ],
    quick: [['✓','Approve Results',true],['▦','Approve Timetable'],['📣','Send Announcement']],
    wPrimary: {type:'chart', title:'Attendance trend (2 wks)', heights:[90,92,88,94,91,60,40,93,95,90,96,92,70,50], hl:11, x:['M','T','W','T','F','S','S','M','T','W','T','F','S','S']},
    wSecondary: {type:'table', title:'Performance snapshot', head:['Class','Avg','Trend'], rows:[['SS 2','72%','▲'],['JSS 3','68%','▲'],['SS 1','75%','▬']]},
    deeperKey: 'approvals', deeperTitle:'Approvals', deeperSub:'5 awaiting sign-off',
  },

  vpacademic: {
    roleLabel: 'VP Academic', who: 'Mrs Ali', avatar: 'MA',
    tenant: 'Greenfield Academy', tenantSub: '', tenantSwitch: false,
    crumb: ['Greenfield Academy', 'Dashboard'],
    rail: ['◉','▦','✎','◷','⚙'], railOn: 0,
    nav: [
      {t:'Dashboard', k:'dash', on:true},
      {group:'Curriculum'},
      {t:'Curriculum', k:'curriculum'},
      {t:'Lesson Plans', k:'lessonplans', cnt:'7'},
      {t:'Assignments', k:'assignments'},
      {t:'Exams', k:'exams'},
      {group:'Staff'},
      {t:'Teachers', k:'teachers'},
      {t:'Grading', k:'grading'},
    ],
    hello: 'Academic overview',
    kpis: [['Classes today','38'],['Lessons completed','24 of 38'],['Curriculum coverage','72%'],['Assignments due','15'],['Exam progress','60%']],
    attention: [
      ['✎','warn','7 lesson plans pending review','Submit by Fri'],
      ['◔','warn','Curriculum behind · Physics','62% vs 75% target'],
      ['▦','','Assessment overview ready','Term 2 mid-point'],
      ['♟','','3 teachers flagged for support','Low completion'],
    ],
    quick: [['✎','Review Lesson Plans',true],['▦','Curriculum Map'],['✉','Message Teachers']],
    wPrimary: {type:'chart', title:'Curriculum coverage trend', heights:[40,46,50,54,58,60,64,66,68,70,71,72], hl:11, x:['','','','','','','','','','','','Now']},
    wSecondary: {type:'table', title:'Subject coverage', head:['Subject','Coverage','Status'], rows:[['Maths','80%','On track'],['English','76%','On track'],['Physics','62%','Behind']]},
    deeperKey: 'lessonplans', deeperTitle:'Lesson plan review', deeperSub:'7 pending review',
  },

  vpadmin: {
    roleLabel: 'VP Administration', who: 'Mr Udo', avatar: 'MU',
    tenant: 'Greenfield Academy', tenantSub: '', tenantSwitch: false,
    crumb: ['Greenfield Academy', 'Dashboard'],
    rail: ['◉','♟','▤','⚲','⚙'], railOn: 0,
    nav: [
      {t:'Dashboard', k:'dash', on:true},
      {group:'Operations'},
      {t:'Staff', k:'staff'},
      {t:'Requests', k:'requests', cnt:'14'},
      {t:'Inventory', k:'inventory', cnt:'5'},
      {t:'Transport', k:'transport', cnt:'2'},
      {t:'Hostel', k:'hostel'},
      {t:'Maintenance', k:'maintenance'},
    ],
    hello: 'Operations · today',
    kpis: [['Staff attendance','92%'],['Open requests','14','','down'],['Inventory alerts','5'],['Transport issues','2','','down']],
    attention: [
      ['◔','warn','5 leave requests','Awaiting approval'],
      ['⚲','warn','3 maintenance requests','1 urgent · Block C'],
      ['!','warn','2 incident reports','Logged today'],
      ['▤','','Inventory low · stationery','Reorder threshold'],
    ],
    quick: [['✓','Review Requests',true],['!','Log Incident'],['▤','Inventory']],
    wPrimary: {type:'feed', title:'Operational alerts', rows:[['Urgent: AC fault · Block C','18 min ago'],['Bus 3 running late','40 min ago'],['Stationery below threshold','2h ago'],['Leave request · J. Bello','3h ago']]},
    wSecondary: {type:'table', title:'Maintenance queue', head:['Item','Area','Status'], rows:[['AC unit','Block C','Urgent'],['Projector','Lab 2','Open'],['Plumbing','Hostel','Scheduled']]},
    deeperKey: 'requests', deeperTitle:'Requests', deeperSub:'leave & maintenance queue',
  },

  classteacher: {
    roleLabel: 'Class Teacher', who: 'Ms Bant', avatar: 'MB',
    tenant: 'Greenfield Academy', tenantSub: '', tenantSwitch: false,
    crumb: ['Greenfield Academy', 'Dashboard'],
    rail: ['◉','♟','◷','✉','⚙'], railOn: 0,
    nav: [
      {t:'Dashboard', k:'dash', on:true},
      {group:'My class · 9B'},
      {t:'Students', k:'students', cnt:'30'},
      {t:'Attendance', k:'attendance'},
      {t:'Performance', k:'performance'},
      {t:'Behaviour', k:'behaviour', cnt:'1'},
      {group:'Home'},
      {t:'Parent Messages', k:'messages', cnt:'3'},
    ],
    hello: 'Good morning · 9B',
    kpis: [['Total students','30'],['Present today','28','▲'],['Absent today','2','','down'],['Outstanding fees','₦80k','','down'],['Behaviour alerts','1','','down']],
    attention: [
      ['◷','warn','2 students absent','No reason logged'],
      ['!','warn','1 behaviour alert','Incident · break time'],
      ['✉','','3 parent messages','2 unread'],
      ['🎂','ok','2 birthdays this week','Send a note'],
    ],
    quick: [['✓','Take Attendance',true],['✉','Message Parents'],['＋','Add Note']],
    wPrimary: {type:'chart', title:'Class attendance (2 wks)', heights:[93,90,96,88,92,0,0,95,90,93,86,94,0,0], hl:10, x:['M','T','W','T','F','S','S','M','T','W','T','F','S','S']},
    wSecondary: {type:'feed', title:'Parent messages', rows:[['Re: Tomi absence','22 min ago'],['Trip consent · A. Musa','1h ago'],['Question about homework','3h ago']]},
    deeperKey: 'attendance', deeperTitle:'Class attendance', deeperSub:'9B · 30 students · today',
  },

  librarian: {
    roleLabel: 'Librarian', who: 'Mr Sani', avatar: 'MS',
    tenant: 'Greenfield Academy', tenantSub: '', tenantSwitch: false,
    crumb: ['Greenfield Academy', 'Dashboard'],
    rail: ['◉','▤','↺','◷','⚙'], railOn: 0,
    nav: [
      {t:'Dashboard', k:'dash', on:true},
      {group:'Library'},
      {t:'Catalogue', k:'catalogue'},
      {t:'Issued', k:'issued', cnt:'142'},
      {t:'Returns', k:'returns'},
      {t:'Reservations', k:'reservations', cnt:'9'},
      {t:'Overdue', k:'overdue', cnt:'17'},
      {t:'Inventory', k:'inventory'},
    ],
    hello: 'Library · today',
    kpis: [['Books issued','142'],['Books returned','98'],['Overdue','17','','down'],['Reservations','9']],
    attention: [
      ['◷','warn','17 overdue books','Send reminders'],
      ['↺','warn','9 reservations to fulfil','3 ready for pickup'],
      ['▤','','Inventory: 3 titles low','Below 2 copies'],
      ['＋','','12 new arrivals','Awaiting cataloguing'],
    ],
    quick: [['↧','Issue Book',true],['↺','Return Book'],['＋','Add Title']],
    wPrimary: {type:'chart', title:'Borrowing (2 wks)', heights:[40,55,48,62,70,30,18,58,66,72,60,80,35,20], hl:11, x:['M','T','W','T','F','S','S','M','T','W','T','F','S','S']},
    wSecondary: {type:'table', title:'Recent borrowing', head:['Student','Title','Due'], rows:[['A. Rivera','Things Fall Apart','12 Jun'],['M. Jones','Half of a Yellow Sun','14 Jun'],['S. Kemi','Purple Hibiscus','15 Jun']]},
    deeperKey: 'overdue', deeperTitle:'Overdue books', deeperSub:'17 overdue · send reminders',
  },

};
