import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import localFont from 'next/font/local';

import '@workspace/ui/globals.css';
import { AppSidebar } from '@workspace/ui/custom/app-sidebar';
import {
  SidebarInset,
  SidebarProvider,
} from '@workspace/ui/components/sidebar';
import { ThemeProvider } from './providers/theme-provider';
import { SiteHeader } from './components/site-header';
import { ColorScheme } from '@workspace/ui/custom/colors/color-scheme';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const cookieStore = await cookies();
   const defaultOpen = cookieStore.get('sidebar_state')?.value === 'true';
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider defaultOpen={defaultOpen}>
              <AppSidebar />
              <SidebarInset>
                <SiteHeader />
                <main>{children}</main>
              </SidebarInset>
            </SidebarProvider>
            <ColorScheme />
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
