export type SensitiveOperationCategory =
  | 'governance'
  | 'financial'
  | 'account_security'
  | 'data_protection'
  | 'platform';

export interface SensitiveOperationDefinition {
  operation: string;
  label: string;
  description: string;
  category: SensitiveOperationCategory;
  requiresStepUp: boolean;
  requiresMakerChecker: boolean;
  freshnessMinutes: number;
  requiredClearanceLevel: number;
  requiredPermission: string | null;
}

/**
 * Bootstrap catalog for server-owned sensitive operations.
 *
 * The database row is authoritative at runtime and is editable only through
 * the platform governance API. This catalog gives migrations/seeding and
 * route decorators one reviewed, versioned source of operation identifiers.
 */
export const SENSITIVE_OPERATION_CATALOG = [
  {
    operation: 'roles.create',
    label: 'Create roles',
    description: 'Create a role that can grant access to school data.',
    category: 'governance',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'roles.create',
  },
  {
    operation: 'roles.update',
    label: 'Change roles',
    description: 'Change role clearance or access boundaries.',
    category: 'governance',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'roles.edit',
  },
  {
    operation: 'roles.delete',
    label: 'Delete roles',
    description: 'Permanently remove a role definition.',
    category: 'governance',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'roles.delete',
  },
  {
    operation: 'roles.custom.level7.create',
    label: 'Create management-level roles',
    description: 'Create a custom role at management clearance.',
    category: 'governance',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 8,
    requiredPermission: 'roles.create',
  },
  {
    operation: 'permissions.modify',
    label: 'Change permission assignments',
    description: 'Change permission pools or their clearance boundaries.',
    category: 'governance',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'roles.edit',
  },
  {
    operation: 'users.role.assign',
    label: 'Assign user roles',
    description: 'Change a user profile role or access level.',
    category: 'governance',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'users.edit',
  },
  {
    operation: 'users.create',
    label: 'Create staff accounts',
    description: 'Create a user directly with school access.',
    category: 'governance',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'users.create',
  },
  {
    operation: 'security-policy.update',
    label: 'Change school security policy',
    description:
      'Change authentication, session, or emergency security policy.',
    category: 'governance',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'settings.security',
  },
  {
    operation: 'financial.transactions',
    label: 'Post financial transactions',
    description: 'Create, adjust, complete, or refund a payment.',
    category: 'financial',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 5,
    requiredPermission: 'payments.edit',
  },
  {
    operation: 'financial.fee-structure.update',
    label: 'Change fee structures',
    description: 'Create or change the fees charged by a school.',
    category: 'financial',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 5,
    requiredPermission: 'fees.edit',
  },
  {
    operation: 'financial.payout',
    label: 'Approve payouts',
    description: 'Release a payout or withdrawal from school funds.',
    category: 'financial',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 5,
    requiredPermission: 'payments.edit',
  },
  {
    operation: 'account.password.change',
    label: 'Change account password',
    description: 'Replace the signed-in user’s password.',
    category: 'account_security',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 0,
    requiredPermission: null,
  },
  {
    operation: 'account.email.change',
    label: 'Change account email',
    description: 'Replace the verified sign-in email address.',
    category: 'account_security',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 0,
    requiredPermission: null,
  },
  {
    operation: 'mfa.method.add',
    label: 'Add an MFA method',
    description: 'Add an authenticator app, email, SMS, or security key.',
    category: 'account_security',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 0,
    requiredPermission: null,
  },
  {
    operation: 'mfa.method.remove',
    label: 'Remove an MFA method',
    description: 'Disable or delete an enrolled authentication method.',
    category: 'account_security',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 0,
    requiredPermission: null,
  },
  {
    operation: 'mfa.recovery.generate',
    label: 'Generate recovery codes',
    description: 'Replace the account’s one-time recovery codes.',
    category: 'account_security',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 0,
    requiredPermission: null,
  },
  {
    operation: 'biometrics.enroll',
    label: 'Add a biometric passkey',
    description:
      'Enroll Face ID, Touch ID, Windows Hello, or device biometrics.',
    category: 'account_security',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 0,
    requiredPermission: null,
  },
  {
    operation: 'biometrics.remove',
    label: 'Remove a biometric passkey',
    description: 'Revoke a biometric passkey from the account.',
    category: 'account_security',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 0,
    requiredPermission: null,
  },
  {
    operation: 'users.force-logout',
    label: 'Force account sign-out',
    description: 'Revoke another user’s active sessions.',
    category: 'account_security',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'users.edit',
  },
  {
    operation: 'users.password.reset',
    label: 'Reset another user’s password',
    description: 'Replace another user’s sign-in password.',
    category: 'account_security',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'users.edit',
  },
  {
    operation: 'students.delete',
    label: 'Delete student records',
    description: 'Permanently remove a student record.',
    category: 'data_protection',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'students.delete',
  },
  {
    operation: 'users.delete',
    label: 'Remove users from a school',
    description: 'Remove a user profile and its school access.',
    category: 'data_protection',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'users.delete',
  },
  {
    operation: 'grades.override',
    label: 'Override grades',
    description: 'Change an already recorded grade or bulk grading result.',
    category: 'data_protection',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'grades.edit',
  },
  {
    operation: 'data.bulk-import',
    label: 'Bulk import school data',
    description: 'Import student, grade, fee, or user records in bulk.',
    category: 'data_protection',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'students.import',
  },
  {
    operation: 'data.bulk-delete',
    label: 'Bulk delete school data',
    description: 'Permanently remove a set of school records.',
    category: 'data_protection',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 8,
    requiredPermission: 'users.delete',
  },
  {
    operation: 'data.export',
    label: 'Export protected data',
    description: 'Export student, financial, or other personal data.',
    category: 'data_protection',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 8,
    requiredPermission: 'reports.export',
  },
  {
    operation: 'backup.restore',
    label: 'Restore a backup',
    description: 'Replace live data with a stored backup.',
    category: 'data_protection',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 9,
    requiredPermission: 'platform.backup',
  },
  {
    operation: 'system.configuration',
    label: 'Change system configuration',
    description: 'Change platform or tenant-wide operational configuration.',
    category: 'data_protection',
    requiresStepUp: true,
    requiresMakerChecker: true,
    freshnessMinutes: 5,
    requiredClearanceLevel: 8,
    requiredPermission: 'settings.school',
  },
  {
    operation: 'ai.settings.update',
    label: 'Change AI settings',
    description: 'Change AI providers, models, limits, or school AI policy.',
    category: 'platform',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 7,
    requiredPermission: 'ai.configure',
  },
  {
    operation: 'breach.response',
    label: 'Run breach response',
    description: 'Revoke sessions or rotate secrets during an incident.',
    category: 'platform',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 9,
    requiredPermission: 'platform.security',
  },
  {
    operation: 'tenant.provision',
    label: 'Provision a tenant',
    description: 'Create or configure a school tenant.',
    category: 'platform',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 9,
    requiredPermission: 'platform.tenants',
  },
  {
    operation: 'tenant.suspend',
    label: 'Suspend or reactivate a tenant',
    description: 'Change whether an entire school can use the platform.',
    category: 'platform',
    requiresStepUp: true,
    requiresMakerChecker: false,
    freshnessMinutes: 5,
    requiredClearanceLevel: 9,
    requiredPermission: 'platform.tenants',
  },
] as const satisfies readonly SensitiveOperationDefinition[];

export type SensitiveOperationName =
  (typeof SENSITIVE_OPERATION_CATALOG)[number]['operation'];

export const SENSITIVE_OPERATION_NAMES = SENSITIVE_OPERATION_CATALOG.map(
  ({ operation }) => operation,
) as SensitiveOperationName[];

export function getSensitiveOperationDefinition(
  operation: string,
): SensitiveOperationDefinition | undefined {
  return SENSITIVE_OPERATION_CATALOG.find(
    (definition) => definition.operation === operation,
  );
}
